apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-buvf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0066-tenant/tkrw-pr714-0075-0066-app/devfile-sample-buvf@sha256:4aaf137216ada28077b5f120dee081ed3130f9f8539a58eb74aa84b194b19a12
        name: my-nodejs
        resources: {}
status: {}
